# Generated by Django 5.0.4 on 2024-05-07 01:45

from django.db import migrations

def populate_status(apps, schemaeditor):
    entries = {
        "draft": "A post that is not ready to be published",
        "published": "A post available for all to see",
        "archived": "An older post available ini the archive only"
    }
    Status = apps.get_model("posts", "Status")
    for key, value in entries.items():
        status_obj = Status(name=key, description=value)
        status_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [migrations.RunPython(populate_status)]
